# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 24) do

  create_table "categories", :force => true do |t|
    t.column "name",        :string,   :limit => 30
    t.column "description", :text
    t.column "url",         :string,   :limit => 15
    t.column "tags",        :string,   :limit => 50
    t.column "created_on",  :datetime
    t.column "updated_on",  :datetime
  end

  create_table "categories_posts", :force => true do |t|
    t.column "category_id", :integer
    t.column "post_id",     :integer
  end

  create_table "comment_versions", :force => true do |t|
    t.column "comment_id",       :integer
    t.column "version",          :integer
    t.column "person_id",        :integer
    t.column "contents",         :text
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
    t.column "commentable_id",   :integer
    t.column "commentable_type", :string
  end

  create_table "comments", :force => true do |t|
    t.column "person_id",        :integer
    t.column "contents",         :text
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
    t.column "commentable_id",   :integer
    t.column "commentable_type", :string
    t.column "version",          :integer
  end

  create_table "people", :force => true do |t|
    t.column "account_name",              :string
    t.column "display_name",              :string
    t.column "email_address",             :string
    t.column "old_password",              :string,   :limit => 40
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_on",              :datetime
    t.column "created_on",                :datetime
    t.column "updated_on",                :datetime
    t.column "profile",                   :text
    t.column "has_icon",                  :boolean,                :default => false
    t.column "icon_type",                 :string,   :limit => 4,  :default => "jpg"
  end

  create_table "post_versions", :force => true do |t|
    t.column "post_id",    :integer
    t.column "version",    :integer
    t.column "contents",   :text
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
    t.column "person_id",  :integer
    t.column "parent_id",  :integer,  :default => 0
  end

  create_table "posts", :force => true do |t|
    t.column "title",      :string
    t.column "contents",   :text
    t.column "version",    :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
    t.column "person_id",  :integer
    t.column "permalink",  :string
    t.column "parent_id",  :integer,  :default => 0
    t.column "type",       :string
  end

  create_table "settings", :force => true do |t|
    t.column "person_id",  :integer
    t.column "name",       :string,   :limit => 30
    t.column "value",      :string,   :limit => 50
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

end
